import React, { Fragment } from 'react';

const Categories = () => {
    return ( 
        <Fragment>
            <div>Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories </div>
            <div>Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories </div>
            <div>Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories Categories </div>    
        </Fragment>
        
     );
}
 
export default Categories;